import base64
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage


def image_to_base64(img_path):
    with open(img_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")

def describe_image(image_path, base_caption, model_name="llava"):
    """Use a local Vision LLM via Ollama to describe an image in detailed structure, guided by a short caption."""
    
    prompt = f"""You are an expert visual scene describer. 
I am providing you with an image and a short preliminary caption: "{base_caption}"
Look at the provided image and generate an extremely detailed description expanding upon the caption.
You MUST start with a new line after finishing every sentence.
You MUST structure your response EXACTLY using the following headings :

Objects and Items:
[Provide detailed description here]

Spatial Layout:
[Provide detailed description here.]

Lighting and Atmosphere:
[Provide detailed description here.]

People and Interactions:
[Provide detailed description here. If no people, state so.]

Visual Elements:
[Provide detailed description here.]

Context and Setting:
[Provide detailed description here.]
"""
 
    llm = ChatOllama(model=model_name, temperature=0.7)
    print(f"Describing image: '{image_path}' using {model_name}...\n")
    
    try:
        image_b64 = image_to_base64(image_path)
        message = HumanMessage(
            content=[
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": f"data:image/jpeg;base64,{image_b64}"},
            ]
        )
        response = llm.invoke([message])
        return response.content
    except Exception as e:
        return f"Error connecting to Ollama: {e}\nPlease ensure Ollama is running locally and the vision model (e.g., '{model_name}') is installed."

if selected_image_path:
    # Pass both the image path and the short 'caption' generated by BLIP earlier
    detailed_notes = describe_image(selected_image_path, caption, model_name="llava")
    print(detailed_notes)
else:
    print("No image selected.")